#!/bin/bash

gnuplot << TOEND

                      # size 3.5,2.62
set terminal epslatex color colortext
set output 'fomegb2.tex'

set key top center
set xtics 60
set grid xtics ytics
set mxtics
set mytics
#set xzeroaxis linetype 1 lc 0 linewidth 2.5
#set yzeroaxis linetype 1 lc 0 linewidth 2.5


set xrange [3:357]
set yrange [0:20]

           # eps postscript term required for /Symbols
#set xlabel "{/Symbol d} (ppm)" 
set xlabel 'Dihedral $\phi$ (degrees)'
set ylabel '\$S(\phi)$'

set bmargin 4

#f(x) = m*x + b
#fit f(x) 'data.dat' using 1:2 via m, b

#                                   linetype 0 for dotted
#                                   impulses for bars
#                                   nothing for just points
plot "sphi.dat" using 1:((\$3)*100) title 'Gas Phase'   w filledcurve x1 fs pattern 2 lc 7 linetype 1, \
     "sphi.dat" using 1:((\$2)*100) title 'TIP4P Water' w filledcurve x1 fs pattern 7 lc 9 linetype 1, \
     "sphi.dat" using 1:((\$3)*100) notitle             w lines       lw 4            lc 7 linetype 2


TOEND

# this stuff is to streamline eps postscript output
perl -pi -e 's/put\(176/put\(250/g' *tex
perl -pi -e 's/fomegb2/figures\/fomegb\/fomegb2/g' *tex
#rm fit.log
epstopdf *.eps 
rm *.eps
#open plot.pdf

