#!/bin/bash

gnuplot << TOEND

#set term x11 enhanced persist
#set term aqua font "Times-New-Roman,13"
#set term aqua font "Times,13"
#set terminal postscript eps color enhanced "Times" 20
#set terminal postscript eps color enhanced
   
                      # size 3.5,2.62
set terminal epslatex color colortext
set output 'phisphi.tex'

# Setting the output file name --- use for eps postscript
# set output 'plot.eps'

#set title 'Number of atom-pair calculations skipped using AGBP'
#set size square
#set nokey 
set key top center
#set log x
set xtics 60
set y2tic auto
#set ytic auto
#unset ytic
set grid xtics ytics
set mxtics
set mytics
#set xzeroaxis linetype 1 lc 0 linewidth 2.5
#set yzeroaxis linetype 1 lc 0 linewidth 2.5


           # you can flip x-axis numbers in reverse order like this
#set xrange [150:0] 
set xrange [0:360]
set yrange [0:10]
set y2range [0:5]

#            eps postscript term required for /Symbols
#set xlabel "{/Symbol d} (ppm)" 
set xlabel 'Dihedral $\phi$ (degrees)'
set ylabel '\$S(\phi)$'
set y2label "Relative energy (kcal/mol)"
#set terminal png nocrop
#set output 'graph.png'

set bmargin 4

#f(x) = m*x + b
#fit f(x) 'data.dat' using 1:2 via m, b

#                                   linetype 0 for dotted
#                                   impulses for bars
#                                   nothing for just points
plot "sphi.dat" using 1:((\$3)*100) title 'Gas Phase'   w filledcurves fs pattern 2 lc 7 linetype 1, \
     "sphi.dat" using 1:((\$2)*100) title 'TIP4P Water' w filledcurves fs pattern 7 lc 9 linetype 1, \
     "sphi.dat" using 1:((\$3)*100) notitle             w lines       lw 4            lc 7 linetype 2, \
     "energy.dat" using 1:4 title 'OPLS/CM1A' w linespoints pointtype 4 linetype 1 lc 7 lw 3 axes x1y2, \
     "energy.dat" using 1:5 title 'MP2/6-311G(d)' w linespoints pointtype 3 linetype 1 lc 7 lw 3 axes x1y2

TOEND

# this stuff is to streamline eps postscript output
perl -pi -e 's/put\(176/put\(250/g' *tex
perl -pi -e 's/phisphi/figures\/phisphi\/phisphi/g' *tex
#rm fit.log
epstopdf *.eps 
rm *.eps
#open plot.pdf

