#!/bin/bash

gnuplot << TOEND

#set term x11 enhanced persist
#set term aqua font "Times-New-Roman,13"
#set term aqua font "Times,13"
#set terminal postscript eps color enhanced "Times" 20
#set terminal postscript eps color enhanced
   
                      # size 3.5,2.62
set terminal epslatex size 3.5,2.62 color colortext
set output 'chf3-pol.tex'

# Setting the output file name --- use for eps postscript
# set output 'plot.eps'

#set title ""
set size square
#set nokey 
#set xtics 1
#set ytic auto
#unset ytic
set grid xtics ytics
set mxtics
set mytics
#set xzeroaxis linetype 1 lc 0 linewidth 2.5
#set yzeroaxis linetype 1 lc 0 linewidth 2.5


           # you can flip x-axis numbers in reverse order like this
#set xrange [150:0] 
set xrange [0:1]
set yrange [-140:0]

#            eps postscript term required for /Symbols
#set xlabel "{/Symbol d} (ppm)" 
set xlabel '$\lambda$'
set ylabel '\$G^\prime_{\textrm{pol},i}$' 

#set terminal png nocrop
#set output 'graph.png'

set bmargin 4

#f(x) = m*x + b
#fit f(x) 'data.dat' using 1:4 via m, b

#                                   linetype 0 for dotted
#                                   impulses for bars
#                                   nothing for just points
plot "data.dat" using 1:2 title 'C' w linespoints pointtype 4 linetype 1 lc 7 lw 3, \
     "data.dat" using 1:3 title 'CA' w linespoints pointtype 3 linetype 1 lc 7 lw 3, \
     "data.dat" using 1:4 title 'H $\rightarrow$ F' w linespoints pointtype 9 linetype 1 lc 7 lw 3
     #f(x) linetype 1 lc 9 lw 3 title 'fit: y = 0.7112x - 0.3804' 
     #title 'fit: y = 0.0013x - 0.0074'

TOEND

# this stuff is to streamline eps postscript output
perl -pi -e 's/put\(176/put\(250/g' *tex
perl -pi -e 's/chf3-pol/figures\/chf3-pol\/chf3-pol/g' *tex
#rm fit.log
epstopdf *.eps 
rm *.eps
#open plot.pdf

